CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE branches (id BIGSERIAL PRIMARY KEY, code CHAR(2) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, phone VARCHAR(50), address TEXT, timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Bangkok', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS staff_code VARCHAR(40);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS staff_type VARCHAR(30) DEFAULT 'PHYSIOTHERAPIST';
ALTER TABLE staff ADD COLUMN IF NOT EXISTS license_no VARCHAR(100);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS specialization VARCHAR(150);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS commission_eligible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS termination_date DATE;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS commission_after_termination_policy VARCHAR(40) NOT NULL DEFAULT 'CONTINUE_UNTIL_COURSE_END';
CREATE TABLE user_branches (user_id BIGINT NOT NULL REFERENCES users(id), branch_id BIGINT NOT NULL REFERENCES branches(id), is_default BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY (user_id, branch_id));
CREATE TABLE permissions (id BIGSERIAL PRIMARY KEY, code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(150) NOT NULL, module VARCHAR(50) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE role_permissions (role_id BIGINT NOT NULL REFERENCES roles(id), permission_id BIGINT NOT NULL REFERENCES permissions(id), PRIMARY KEY (role_id, permission_id));

CREATE TABLE master_data_values (id BIGSERIAL PRIMARY KEY, data_type VARCHAR(60) NOT NULL, code VARCHAR(60) NOT NULL, name_th VARCHAR(200) NOT NULL, name_en VARCHAR(200), sort_order INTEGER NOT NULL DEFAULT 0, metadata JSONB NOT NULL DEFAULT '{}', active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(data_type, code));
CREATE TABLE payment_methods (id BIGSERIAL PRIMARY KEY, code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL, requires_reference BOOLEAN NOT NULL DEFAULT FALSE, requires_attachment BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE services (id BIGSERIAL PRIMARY KEY, code VARCHAR(40) UNIQUE NOT NULL, name_th VARCHAR(200) NOT NULL, name_en VARCHAR(200), service_type VARCHAR(30) NOT NULL, duration_minutes INTEGER NOT NULL CHECK(duration_minutes > 0), base_price NUMERIC(14,2) NOT NULL CHECK(base_price >= 0), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ);
CREATE TABLE courses (id BIGSERIAL PRIMARY KEY, code VARCHAR(40) UNIQUE NOT NULL, name_th VARCHAR(200) NOT NULL, name_en VARCHAR(200), total_sessions INTEGER NOT NULL CHECK(total_sessions > 0), validity_days INTEGER CHECK(validity_days IS NULL OR validity_days > 0), price NUMERIC(14,2) NOT NULL CHECK(price >= 0), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ);
CREATE TABLE course_items (course_id BIGINT NOT NULL REFERENCES courses(id), service_id BIGINT NOT NULL REFERENCES services(id), quantity INTEGER NOT NULL CHECK(quantity > 0), unit_price NUMERIC(14,2) NOT NULL CHECK(unit_price >= 0), PRIMARY KEY(course_id, service_id));

CREATE TABLE hn_sequences (branch_id BIGINT NOT NULL REFERENCES branches(id), year_month CHAR(6) NOT NULL, last_number INTEGER NOT NULL DEFAULT 0 CHECK(last_number BETWEEN 0 AND 9999), PRIMARY KEY(branch_id, year_month));
CREATE TABLE patients (id BIGSERIAL PRIMARY KEY, hn VARCHAR(20) UNIQUE NOT NULL, registered_branch_id BIGINT NOT NULL REFERENCES branches(id), registered_at TIMESTAMPTZ NOT NULL DEFAULT now(), customer_type VARCHAR(30) NOT NULL, prefix VARCHAR(30) NOT NULL, first_name_th VARCHAR(100) NOT NULL, last_name_th VARCHAR(100) NOT NULL, first_name_en VARCHAR(100), last_name_en VARCHAR(100), nickname VARCHAR(100), gender_code VARCHAR(40) NOT NULL, national_id_hash CHAR(64), national_id_ciphertext TEXT, passport_hash CHAR(64), passport_ciphertext TEXT, birth_date DATE, blood_group_code VARCHAR(20), nationality_code VARCHAR(40), phone VARCHAR(50) NOT NULL, email VARCHAR(255), address JSONB, customer_group_code VARCHAR(60), referral_channel_code VARCHAR(60), insurance_company_code VARCHAR(60), active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ);
CREATE UNIQUE INDEX uq_patient_national_id_hash ON patients(national_id_hash) WHERE national_id_hash IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE rooms (id BIGSERIAL PRIMARY KEY, branch_id BIGINT NOT NULL REFERENCES branches(id), code VARCHAR(40) NOT NULL, name VARCHAR(150) NOT NULL, room_type VARCHAR(60), active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(branch_id, code));
CREATE TABLE appointments (id BIGSERIAL PRIMARY KEY, appointment_no VARCHAR(40) UNIQUE NOT NULL, patient_id BIGINT NOT NULL REFERENCES patients(id), branch_id BIGINT NOT NULL REFERENCES branches(id), provider_staff_id BIGINT NOT NULL REFERENCES staff(id), service_id BIGINT NOT NULL REFERENCES services(id), room_id BIGINT REFERENCES rooms(id), starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED', source VARCHAR(30) NOT NULL DEFAULT 'BACKOFFICE', patient_note TEXT, internal_note TEXT, cancel_reason_code VARCHAR(60), cancelled_at TIMESTAMPTZ, cancelled_by BIGINT REFERENCES users(id), created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(ends_at > starts_at));
ALTER TABLE appointments ADD CONSTRAINT appointments_no_provider_overlap EXCLUDE USING gist (provider_staff_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&) WHERE (status IN ('CONFIRMED','ARRIVED','IN_SERVICE'));
CREATE TABLE appointment_events (id BIGSERIAL PRIMARY KEY, appointment_id BIGINT NOT NULL REFERENCES appointments(id), from_status VARCHAR(30), to_status VARCHAR(30) NOT NULL, reason TEXT, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), occurred_by BIGINT REFERENCES users(id), metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE visits (id BIGSERIAL PRIMARY KEY, appointment_id BIGINT UNIQUE NOT NULL REFERENCES appointments(id), patient_id BIGINT NOT NULL REFERENCES patients(id), branch_id BIGINT NOT NULL REFERENCES branches(id), treating_staff_id BIGINT NOT NULL REFERENCES staff(id), course_id BIGINT, check_in_at TIMESTAMPTZ, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, status VARCHAR(30) NOT NULL DEFAULT 'OPEN', created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE sales_transactions (id BIGSERIAL PRIMARY KEY, transaction_no VARCHAR(50) UNIQUE NOT NULL, patient_id BIGINT NOT NULL REFERENCES patients(id), branch_id BIGINT NOT NULL REFERENCES branches(id), transaction_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', subtotal NUMERIC(14,2) NOT NULL CHECK(subtotal >= 0), discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(discount_amount >= 0), tax_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(tax_amount >= 0), total_amount NUMERIC(14,2) NOT NULL CHECK(total_amount >= 0), sold_at TIMESTAMPTZ NOT NULL DEFAULT now(), salesperson_id BIGINT REFERENCES staff(id), created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), cancelled_at TIMESTAMPTZ);
CREATE TABLE sales_items (id BIGSERIAL PRIMARY KEY, sales_transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id), item_type VARCHAR(30) NOT NULL, service_id BIGINT REFERENCES services(id), course_id BIGINT REFERENCES courses(id), description_snapshot VARCHAR(250) NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), unit_price NUMERIC(14,2) NOT NULL CHECK(unit_price >= 0), total_amount NUMERIC(14,2) NOT NULL CHECK(total_amount >= 0));
CREATE TABLE payments (id BIGSERIAL PRIMARY KEY, payment_no VARCHAR(50) UNIQUE NOT NULL, sales_transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id), payment_method_id BIGINT NOT NULL REFERENCES payment_methods(id), amount NUMERIC(14,2) NOT NULL CHECK(amount > 0), status VARCHAR(30) NOT NULL DEFAULT 'PAID', paid_at TIMESTAMPTZ NOT NULL DEFAULT now(), reference_no VARCHAR(150), received_by BIGINT REFERENCES users(id));
CREATE TABLE transaction_cancellations (id BIGSERIAL PRIMARY KEY, transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id), reason_code VARCHAR(60) NOT NULL, reason_text TEXT, cancelled_by BIGINT REFERENCES users(id), cancelled_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE commission_schemes (id BIGSERIAL PRIMARY KEY, code VARCHAR(40) NOT NULL, version INTEGER NOT NULL, effective_from DATE NOT NULL, effective_to DATE, active BOOLEAN NOT NULL DEFAULT TRUE, overflow_policy VARCHAR(40) NOT NULL DEFAULT 'CAP_AT_COMMISSION', after_termination_policy VARCHAR(40) NOT NULL DEFAULT 'CONTINUE_UNTIL_COURSE_END', created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(code, version), CHECK(effective_to IS NULL OR effective_to >= effective_from));
CREATE TABLE commission_tiers (id BIGSERIAL PRIMARY KEY, scheme_id BIGINT NOT NULL REFERENCES commission_schemes(id), tier_order INTEGER NOT NULL, minimum_monthly_sales NUMERIC(14,2) NOT NULL CHECK(minimum_monthly_sales >= 0), maximum_monthly_sales NUMERIC(14,2), commission_rate NUMERIC(7,4) NOT NULL CHECK(commission_rate >= 0), active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(scheme_id, tier_order), CHECK(maximum_monthly_sales IS NULL OR maximum_monthly_sales >= minimum_monthly_sales));
ALTER TABLE commission_tiers ADD CONSTRAINT commission_tier_no_overlap EXCLUDE USING gist (scheme_id WITH =, numrange(minimum_monthly_sales, COALESCE(maximum_monthly_sales + 0.01, NULL), '[)') WITH &&) WHERE (active);
CREATE TABLE treatment_fee_rules (id BIGSERIAL PRIMARY KEY, version INTEGER NOT NULL, employee_id BIGINT REFERENCES staff(id), employee_group VARCHAR(60), service_id BIGINT REFERENCES services(id), fee_type VARCHAR(20) NOT NULL, fee_value NUMERIC(14,4) NOT NULL CHECK(fee_value >= 0), percentage_base VARCHAR(50), effective_from DATE NOT NULL, effective_to DATE, active BOOLEAN NOT NULL DEFAULT TRUE, CHECK((fee_type = 'FIXED' AND percentage_base IS NULL) OR fee_type = 'PERCENTAGE'));
CREATE TABLE monthly_commission_closings (id BIGSERIAL PRIMARY KEY, closing_month DATE NOT NULL, employee_id BIGINT NOT NULL REFERENCES staff(id), monthly_course_sales NUMERIC(14,2) NOT NULL, scheme_id BIGINT NOT NULL REFERENCES commission_schemes(id), calculated_commission_rate NUMERIC(7,4) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'OPEN', closed_at TIMESTAMPTZ, closed_by BIGINT REFERENCES users(id), UNIQUE(closing_month, employee_id));
CREATE TABLE patient_courses (id BIGSERIAL PRIMARY KEY, course_id VARCHAR(60) UNIQUE NOT NULL, receipt_no VARCHAR(60) NOT NULL, sales_transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id), patient_id BIGINT NOT NULL REFERENCES patients(id), package_id BIGINT NOT NULL REFERENCES courses(id), package_name_snapshot VARCHAR(250) NOT NULL, sale_date DATE NOT NULL, sale_month DATE NOT NULL, seller_employee_id BIGINT NOT NULL REFERENCES staff(id), case_owner_employee_id BIGINT NOT NULL REFERENCES staff(id), seller_name_snapshot VARCHAR(250) NOT NULL, course_price NUMERIC(14,2) NOT NULL CHECK(course_price >= 0), total_visits INTEGER NOT NULL CHECK(total_visits > 0), commission_status VARCHAR(30) NOT NULL DEFAULT 'PROVISIONAL', commission_scheme_id BIGINT REFERENCES commission_schemes(id), commission_scheme_version INTEGER, provisional_commission_rate NUMERIC(7,4), locked_commission_rate NUMERIC(7,4), total_course_commission_pool NUMERIC(14,2), commission_allocation_per_visit NUMERIC(14,2), commission_generated_date TIMESTAMPTZ NOT NULL DEFAULT now(), visits_used INTEGER NOT NULL DEFAULT 0 CHECK(visits_used >= 0), gross_commission_allocated_total NUMERIC(14,2) NOT NULL DEFAULT 0, owner_net_commission_released_total NUMERIC(14,2) NOT NULL DEFAULT 0, substitute_treatment_fee_total NUMERIC(14,2) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', valid_until DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(visits_used <= total_visits));
CREATE TABLE shared_course_members (patient_course_id BIGINT NOT NULL REFERENCES patient_courses(id), patient_id BIGINT NOT NULL REFERENCES patients(id), role VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', PRIMARY KEY(patient_course_id, patient_id));
CREATE TABLE course_ledger_entries (id BIGSERIAL PRIMARY KEY, patient_course_id BIGINT NOT NULL REFERENCES patient_courses(id), entry_type VARCHAR(30) NOT NULL, quantity INTEGER NOT NULL, balance_after INTEGER NOT NULL CHECK(balance_after >= 0), related_visit_id BIGINT REFERENCES visits(id), related_transfer_id BIGINT, reversal_of_id BIGINT REFERENCES course_ledger_entries(id), reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT REFERENCES users(id));
CREATE TABLE course_transfers (id BIGSERIAL PRIMARY KEY, transfer_no VARCHAR(60) UNIQUE NOT NULL, patient_course_id BIGINT NOT NULL REFERENCES patient_courses(id), from_patient_id BIGINT NOT NULL REFERENCES patients(id), to_patient_id BIGINT NOT NULL REFERENCES patients(id), quantity INTEGER NOT NULL CHECK(quantity > 0), status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED', reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT REFERENCES users(id));
CREATE TABLE commission_allocations (id BIGSERIAL PRIMARY KEY, visit_id BIGINT NOT NULL REFERENCES visits(id), patient_course_id BIGINT NOT NULL REFERENCES patient_courses(id), patient_id BIGINT NOT NULL REFERENCES patients(id), case_owner_employee_id BIGINT NOT NULL REFERENCES staff(id), treating_employee_id BIGINT NOT NULL REFERENCES staff(id), visit_date DATE NOT NULL, gross_commission_allocation NUMERIC(14,2) NOT NULL, treatment_fee_rule_id BIGINT REFERENCES treatment_fee_rules(id), treatment_fee_type VARCHAR(20), treatment_fee_rate_or_amount NUMERIC(14,4), treatment_fee_calculation_base NUMERIC(14,2), treatment_fee_amount NUMERIC(14,2) NOT NULL DEFAULT 0, owner_net_commission NUMERIC(14,2) NOT NULL, company_top_up_amount NUMERIC(14,2) NOT NULL DEFAULT 0, overflow_policy_used VARCHAR(40), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT REFERENCES users(id), UNIQUE(visit_id, patient_course_id));
CREATE TABLE audit_logs (id BIGSERIAL PRIMARY KEY, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), actor_user_id BIGINT REFERENCES users(id), branch_id BIGINT REFERENCES branches(id), action VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id VARCHAR(80) NOT NULL, before_data JSONB, after_data JSONB, reason TEXT, request_id VARCHAR(100));

CREATE INDEX idx_patients_phone ON patients(phone);
CREATE INDEX idx_appointments_branch_time ON appointments(branch_id, starts_at);
CREATE INDEX idx_sales_branch_date ON sales_transactions(branch_id, sold_at);
CREATE INDEX idx_courses_owner ON patient_courses(case_owner_employee_id, sale_month);
CREATE INDEX idx_course_ledger_course ON course_ledger_entries(patient_course_id, created_at);
CREATE INDEX idx_allocations_date ON commission_allocations(visit_date, treating_employee_id);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id, occurred_at);

INSERT INTO roles(code,name) VALUES ('RECEPTIONIST','Receptionist'),('FINANCE','Finance'),('REPORT_VIEWER','Report Viewer') ON CONFLICT(code) DO NOTHING;
INSERT INTO payment_methods(code,name,requires_reference) VALUES ('CASH','Cash',false),('TRANSFER','Bank Transfer',true),('QR','QR Payment',true),('CARD','Credit Card',true) ON CONFLICT(code) DO NOTHING;
INSERT INTO commission_schemes(code,version,effective_from) VALUES ('DEFAULT',1,'2026-01-01') ON CONFLICT(code,version) DO NOTHING;
INSERT INTO commission_tiers(scheme_id,tier_order,minimum_monthly_sales,maximum_monthly_sales,commission_rate) SELECT id,1,0,59999,0.05 FROM commission_schemes WHERE code='DEFAULT' AND version=1 ON CONFLICT DO NOTHING;
INSERT INTO commission_tiers(scheme_id,tier_order,minimum_monthly_sales,maximum_monthly_sales,commission_rate) SELECT id,2,60000,69999,0.06 FROM commission_schemes WHERE code='DEFAULT' AND version=1 ON CONFLICT DO NOTHING;
INSERT INTO commission_tiers(scheme_id,tier_order,minimum_monthly_sales,maximum_monthly_sales,commission_rate) SELECT id,3,70000,79999,0.07 FROM commission_schemes WHERE code='DEFAULT' AND version=1 ON CONFLICT DO NOTHING;
INSERT INTO commission_tiers(scheme_id,tier_order,minimum_monthly_sales,maximum_monthly_sales,commission_rate) SELECT id,4,80000,89999,0.08 FROM commission_schemes WHERE code='DEFAULT' AND version=1 ON CONFLICT DO NOTHING;
INSERT INTO commission_tiers(scheme_id,tier_order,minimum_monthly_sales,maximum_monthly_sales,commission_rate) SELECT id,5,90000,NULL,0.10 FROM commission_schemes WHERE code='DEFAULT' AND version=1 ON CONFLICT DO NOTHING;
