import { useEffect,useState } from 'react'; import { AppShell,roleNames,type Role } from './components/AppShell'; import { PageRouter } from './pages';
const defaults:Record<Role,string>={admin:'dashboard',manager:'dashboard',frontdesk:'patients',physio:'my-appointments'};
const accounts:{role:Role;title:string;user:string;description:string}[]=[
 {role:'admin',title:'System Admin',user:'admin',description:'Configure branches, staff, services & rules'},
 {role:'frontdesk',title:'Front Desk',user:'frontdesk',description:'Patients, appointments, checkout & courses'},
 {role:'physio',title:'Physiotherapist',user:'physio',description:'Treat assigned patients & track commission'},
 {role:'manager',title:'Manager',user:'manager',description:'Dashboard, reports & transaction audit'}
];
function read(){const [role,path]=location.hash.slice(1).split('/');return {role:(role as Role)||null,path:path||''}}
export default function App(){const initial=read();const [role,setRole]=useState<Role|null>(initial.role);const [path,setPath]=useState(initial.path||(initial.role?defaults[initial.role]:'branches'));useEffect(()=>{const fn=()=>{const v=read();setRole(v.role);if(v.role)setPath(v.path||defaults[v.role])};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);const enter=(r:Role)=>{setRole(r);setPath(defaults[r]);location.hash=`${r}/${defaults[r]}`};if(!role)return <Login onEnter={enter}/>;return <AppShell role={role} path={path} onNavigate={p=>{setPath(p);location.hash=`${role}/${p}`}} onLogout={()=>{setRole(null);location.hash=''}}><PageRouter path={path}/></AppShell>}
function Login({onEnter}:{onEnter:(r:Role)=>void}){const [username,setUsername]=useState('');return <div className="reference-login"><section className="login-showcase"><div className="login-logo"><span>⌁</span>PhysioCare Clinic ERP</div><div><h1>Run your clinic&apos;s entire workflow, end to end.</h1><p>An internal system for clinic staff — registration, appointments, treatment, checkout, course balances and reporting, all handled by your team on behalf of every patient.</p><div className="feature-grid"><span>▣ Appointments & Visits</span><span>▤ Course Balance Tracking</span><span>▦ Multi-Branch Access</span><span>% Commission & Reports</span></div></div><small>© 2026 PhysioCare Clinic. Interactive product mock-up — no real data.</small></section><section className="login-access"><div className="login-form"><h2>Sign in to your workspace</h2><p>Enter your credentials, or pick a demo account below.</p><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="e.g. frontdesk"/></label><label>Password<input type="password" placeholder="demo"/></label><button className="primary sign-in" onClick={()=>onEnter(accounts.find(a=>a.user===username)?.role??'frontdesk')}>Sign In</button><div className="demo-divider"><i/>Demo Accounts<i/></div>{accounts.map(a=><button className="demo-account" key={a.role} onClick={()=>onEnter(a.role)}><span className="demo-icon">{a.title.slice(0,2)}</span><span><b>{a.title}</b><small>{a.description}</small></span><code>{a.user}</code></button>)}</div></section></div>}
